---
- name: make /var/www dir
  file:
    path: /var/www
    state: directory
    mode: 0755

- debug:
    msg: "Name={{ item.key }} content={{ item.value.content }}"
  with_dict: "{{ certificates }}"

- name: copy wildcard cert from vault
  copy:
    content: "{{ item.content }}"
    dest: "/etc/ssl/private/{{ item.name }}"
    owner: root
    group: root
    mode: "u=rw,g=r,o="
  no_log: false
  with_items:
    - certificates
  when: certificates 
    
- name: copy over custom 403
  copy:
    src: files/haproxy-403.http
    dest: /var/www/403.http
    owner: root
    group: haproxy
    mode: '0644'
