---
- name: make /var/www dir
  file:
    path: /var/www
    state: directory
    mode: 0755

- name: copy wildcard cert from vault
  copy:
    content: "{{ item.content }}"
    dest: "/etc/ssl/private/{{ item.name }}"
    owner: root
    group: root
    mode: "744"
  no_log: true
  with_items:
    - "{{ certificates }}"
  when: certificates 
    
- name: copy over custom 403
  copy:
    src: files/haproxy-403.http
    dest: /var/www/403.http
    owner: root
    group: haproxy
    mode: '0644'
